#!/usr/bin/env bash

## Author  : Aditya Shakya
## Mail    : adi1090x@gmail.com
## Github  : @adi1090x
## Twitter : @adi1090x

dir="~/.config/polybar/cuts/scripts/rofi"
uptime=$(uptime -p | sed -e 's/up //g')

rofi_command="rofi -theme $dir/tor_control.rasi"

# Options
panel="  TOR Control Panel"
restart="  Restart TOR"
reload="  Reload TOR"
stop="  Stop TOR"
check="  System Check"

# Confirmation
#confirm_exit() {
#	rofi -dmenu\
#		-i\
#		-no-fixed-num-lines\
#		-p "Are You Sure? : "\
#		-theme $dir/confirm.rasi
#}

# Message
#msg() {
#	rofi -theme "$dir/message.rasi" -e "Available Options  -  yes / y / no / n"
#}

# Variable passed to rofi
options="$panel\n$restart\n$reload\n$stop\n$check"

chosen="$(echo -e "$options" | $rofi_command -p "Uptime: $uptime" -dmenu -selected-row 0)"
case $chosen in
    $panel)
		ans=$(confirm_exit &)
		if [[ $ans == "yes" || $ans == "YES" || $ans == "y" || $ans == "Y" ]]; then
			#systemctl poweroff
		elif [[ $ans == "no" || $ans == "NO" || $ans == "n" || $ans == "N" ]]; then
			exit 0
        else
			msg
        fi
        ;;
    $restart)
		ans=$(confirm_exit &)
		if [[ $ans == "yes" || $ans == "YES" || $ans == "y" || $ans == "Y" ]]; then
			systemctl restart tor
		elif [[ $ans == "no" || $ans == "NO" || $ans == "n" || $ans == "N" ]]; then
			exit 0
        else
			msg
        fi
        ;;
    $reload)
		if [[ -f /usr/bin/i3lock ]]; then
			i3lock
		elif [[ -f /usr/bin/betterlockscreen ]]; then
			betterlockscreen -l
		fi
        ;;
    $stop)
		ans=$(confirm_exit &)
		if [[ $ans == "yes" || $ans == "YES" || $ans == "y" || $ans == "Y" ]]; then
			systemctl stop tor
		elif [[ $ans == "no" || $ans == "NO" || $ans == "n" || $ans == "N" ]]; then
			exit 0
        else
			msg
        fi
        ;;
    $check)
		ans=$(confirm_exit &)
		if [[ $ans == "yes" || $ans == "YES" || $ans == "y" || $ans == "Y" ]]; then
			if [[ "$DESKTOP_SESSION" == "Openbox" ]]; then
				systemcheck --verbose --gui --cli
			elif [[ "$DESKTOP_SESSION" == "bspwm" ]]; then
				systemcheck --verbose --gui --cli
			elif [[ "$DESKTOP_SESSION" == "i3" ]]; then
				systemcheck --verbose --gui --cli
			fi
		elif [[ $ans == "no" || $ans == "NO" || $ans == "n" || $ans == "N" ]]; then
			exit 0
        else
			msg
        fi
        ;;
esac
